version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SSL_CACERTFILE: /rootCA.pem
      RABBITMQ_SSL_CERTFILE: /rootCA.pem
      RABBITMQ_SSL_KEYFILE: /rootCA.key
      RABBITMQ_SSL_VERIFY: verify_none
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
    volumes:
      - "./tests/files/rootCA.pem:/rootCA.pem:ro"
      - "./tests/files/rootCA.key:/rootCA.key:ro"
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"

  rabbitmq-management:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_MANAGEMENT_SSL_CACERTFILE: /rootCA.pem
      RABBITMQ_MANAGEMENT_SSL_CERTFILE: /rootCA.pem
      RABBITMQ_MANAGEMENT_SSL_KEYFILE: /rootCA.key
      RABBITMQ_MANAGEMENT_SSL_VERIFY: verify_none
      RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "false"
    volumes:
      - "./tests/files/rootCA.pem:/rootCA.pem:ro"
      - "./tests/files/rootCA.key:/rootCA.key:ro"
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
