name: Tests
on:
  push:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']
        os: [ubuntu-latest]
        stability: [prefer-stable]
        include:
          - laravel: 11.*
            testbench: 9.*
            phpunit: ^10.0
          - laravel: 12.*
            testbench: 10.*
            phpunit: ^11.0
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, curl, dom, mbstring, pcntl, sockets, xml, intl
          coverage: xdebug
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker Compose
        run: |
          docker compose version || {
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          }
      - name: Start Docker container
        run: docker compose up -d
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update --dev
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - name: Execute tests
        run: vendor/bin/phpunit --no-coverage
