name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench: 9.*
          - laravel: 12.*
            testbench: 10.*
        exclude:
          - php: 8.4
            stability: prefer-lowest

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    services:
      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: laravel
          RABBITMQ_DEFAULT_PASS: secret
          RABBITMQ_DEFAULT_VHOST: b2b-field
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 30s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, amqp

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Clear PHPUnit cache
        run: |
          rm -rf .phpunit.cache
          rm -rf .phpunit.result.cache

      - name: Wait for RabbitMQ
        run: |
          echo "Waiting for RabbitMQ to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:15672/api/overview -u laravel:secret >/dev/null 2>&1; then
              echo "RabbitMQ is ready!"
              break
            fi
            echo "Attempt $i/30: RabbitMQ not ready yet, waiting..."
            sleep 2
          done

      - name: Verify RabbitMQ
        run: |
          echo "RabbitMQ Status:"
          curl -u laravel:secret http://localhost:15672/api/overview 2>/dev/null | jq -r '.rabbitmq_version // "Unable to get version"'
          echo "Available vhosts:"
          curl -u laravel:secret http://localhost:15672/api/vhosts 2>/dev/null | jq -r '.[].name // "Unable to get vhosts"'

      - name: Run tests
        env:
          RABBITMQ_HOST: 127.0.0.1
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: laravel
          RABBITMQ_PASSWORD: secret
          RABBITMQ_VHOST: b2b-field
        run: ./run-tests.sh
