name: run-tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1
      XDEBUG_MODE: coverage
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        laravel: [ 11.*, 12.* ]
        include:
          - laravel: 12.*
            testbench: 10.*
          - laravel: 11.*
            testbench: 9.*

    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }}

    services:
      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: laravel
          RABBITMQ_DEFAULT_PASS: secret
          RABBITMQ_DEFAULT_VHOST: laravel-rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 30s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, amqp
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-update
          composer update --prefer-dist --no-suggest

      - name: Wait for RabbitMQ to be ready
        run: |
          timeout 60s bash -c 'until docker exec $(docker ps -q --filter ancestor=rabbitmq:3-management) rabbitmqctl status; do sleep 2; done'

      - name: Execute tests
        env:
          RABBITMQ_HOST: 127.0.0.1
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: laravel
          RABBITMQ_PASSWORD: secret
          RABBITMQ_VHOST: laravel-rabbitmq
        run: |
          vendor/bin/pest --coverage-clover=coverage.clover
